// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Lmx1otkWAt-6fhxoiPTID7qvXgohecA',
    appId: '1:438565490833:web:c936f355052736e4646f30',
    messagingSenderId: '438565490833',
    projectId: 'calories-coach-app',
    authDomain: 'calories-coach-app.firebaseapp.com',
    storageBucket: 'calories-coach-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ9P-v4xx-ohzacqkNS_1VlVf2AK2q_40',
    appId: '1:438565490833:android:c0690c76331ccb06646f30',
    messagingSenderId: '438565490833',
    projectId: 'calories-coach-app',
    storageBucket: 'calories-coach-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2Br8Z4sezei6LV9l6TkBU_MQwzI8x0R0',
    appId: '1:438565490833:ios:8fb5e85f7c2740e8646f30',
    messagingSenderId: '438565490833',
    projectId: 'calories-coach-app',
    storageBucket: 'calories-coach-app.firebasestorage.app',
    iosBundleId: 'com.example.caloriesCoach',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2Br8Z4sezei6LV9l6TkBU_MQwzI8x0R0',
    appId: '1:438565490833:ios:8fb5e85f7c2740e8646f30',
    messagingSenderId: '438565490833',
    projectId: 'calories-coach-app',
    storageBucket: 'calories-coach-app.firebasestorage.app',
    iosBundleId: 'com.example.caloriesCoach',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4Lmx1otkWAt-6fhxoiPTID7qvXgohecA',
    appId: '1:438565490833:web:1d484614293e5f80646f30',
    messagingSenderId: '438565490833',
    projectId: 'calories-coach-app',
    authDomain: 'calories-coach-app.firebaseapp.com',
    storageBucket: 'calories-coach-app.firebasestorage.app',
  );
}
